datapacks/Bookshelf/data/bs.core/functions/out_to_in/0.mcfunction
datapacks/Bookshelf/data/bs.core/functions/out_to_in/1.mcfunction
datapacks/Bookshelf/data/bs.core/functions/out_to_in/2.mcfunction
datapacks/Bookshelf/data/bs.core/functions/out_to_in/3.mcfunction
datapacks/Bookshelf/data/bs.core/functions/out_to_in/4.mcfunction
datapacks/Bookshelf/data/bs.core/functions/out_to_in/5.mcfunction
datapacks/Bookshelf/data/bs.core/functions/out_to_in/6.mcfunction
datapacks/Bookshelf/data/bs.core/functions/out_to_in/7.mcfunction
datapacks/Bookshelf/data/bs.core/functions/out_to_in/8.mcfunction
datapacks/Bookshelf/data/bs.core/functions/out_to_in/9.mcfunction
datapacks/Bookshelf/data/bs.vector/functions/cross_product.mcfunction
datapacks/Bookshelf/data/bs.vector/functions/from_loc.mcfunction
datapacks/Bookshelf/data/bs.vector/functions/from_outputs.mcfunction
datapacks/Bookshelf/data/bs.vector/functions/scalar_product.mcfunction
datapacks/Bookshelf/data/bs.vector/functions/swap_inputs.mcfunction

- **`bs.vector:scalar_product`** implémente le produit scalaire à partir des scores `bs.vector[x,y,z]` et `bs.in[0,1,2]`
- **`bs.vector:cross_product`** implémente le produit vectoriel à partir des mêmes scores
- **`bs.vector:swap_inputs`** échange les valeurs des scores précédents.
- **`bs.vector:from_loc`** copie les valeurs des scores `bs.loc.[x,y,z]` dans `bs.vector.[x,y,z]`
- **`bs.vector:from_outputs`** copie les valeurs des scores `bs.out.[0,1,2]` dans `bs.vector.[x,y,z]`
- **`bs.core:out_to_in/[0-9]`** copie la valeur du score `bs.out.[0-9]` dans `bs.in.[0-9]`

Implémente les produits scalaires / vectoriels et l'échange des entrées "in" / "vector" et "in" / "out"

---

datapacks/Bookshelf/data/bs.bitwise/functions/__load__.mcfunction
datapacks/Bookshelf/data/bs.bitwise/functions/__unload__.mcfunction
datapacks/Bookshelf/data/bs.color/functions/__help__.mcfunction
datapacks/Bookshelf/data/bs.color/functions/__load__.mcfunction
datapacks/Bookshelf/data/bs.color/functions/__unload__.mcfunction
docs/modules/biome.md

- Missing file header in bs.color
- Missing shared objectives in bs.bitwise

🎨 Fix consistency issues

---

docs/quickstart.md

📝 Add Modrinth as installation source

---

docs/CHANGELOG.md
docs/_templates/mods-and-datapacks.md
docs/_templates/related-libraries.md
docs/_templates/tools.md
docs/related/guides-and-tools.md

📝 Add new tools

---

README.md
docs/conf.py
docs/faq.md
docs/index.md
docs/modules/move.md
docs/quickstart.md

📝 Replace the discord link by the link to the new Discord

---

.env.yml
.github/workflows/release.yml
docs/_static/switcher.json
scripts/ci/distribute_release_wf.py

Prepare new Bookshelf version

---

datapacks/Bookshelf/data/bs.math/function/factorial/factorial.mcfunction
docs/CHANGELOG.md

- ✅ I accept to publish my contribution under [MPL v2](http://mozilla.org/MPL/2.0/) License
- ✅ My pull request is linked to an existing issue
- ✅ I have added my contribution to the [changelog](https://github.com/Gunivers/Bookshelf/blob/master/docs/CHANGELOG.md)

Enhance speed of factorial function

---

.github/ISSUE_TEMPLATE/bug_report.md

🐛 Fix some mispellings inside the bug_report.md

---

datapacks/Bookshelf/data/bs.hitbox/function/get_block/registry/0.mcfunction
docs/_static/bookshelf.css
docs/_templates/projects-using-bookshelf.md
docs/_templates/related-libraries.md
docs/_templates/tools.md
docs/contribute/contribution-validation.md
docs/contribute/debug.md
docs/contribute/definitions.md
docs/contribute/documentation.md
docs/contribute/file-format.md
docs/contribute/index.md
docs/contribute/metadata.md
docs/contribute/nomenclature.md
docs/contribute/shared-data.md
docs/contribute/special-functions.md
docs/contribute/tree-structure.md
docs/quickstart.md
docs/related.md
docs/related/guides-and-tools.md
docs/related/related-libraries.md
docs/related/use-bookshelf.md

Fix #224 (update table hover, tabs background (in dark mode), and tabs border)

💄 Fix documentation style

---

.gitignore
.spyglassrc.json
.vscode/settings.json
datapacks/Bookshelf Dev/data/bs.log/function/__load__.mcfunction

🚨 Add spyglass config and improve linting

---

datapacks/Bookshelf/data/bs.schedule/function/cancel/cancel_all.mcfunction
datapacks/Bookshelf/data/bs.schedule/function/cancel/cancel_one.mcfunction
datapacks/Bookshelf/data/bs.schedule/function/cancel/remove_one.mcfunction
datapacks/Bookshelf/data/bs.schedule/function/clear.mcfunction
datapacks/Bookshelf/data/bs.schedule/function/execute/callback.mcfunction
datapacks/Bookshelf/data/bs.schedule/function/execute/context.mcfunction
datapacks/Bookshelf/data/bs.schedule/function/execute/loop.mcfunction
datapacks/Bookshelf/data/bs.schedule/function/execute/splice.mcfunction
datapacks/Bookshelf/data/bs.schedule/function/schedule/schedule.mcfunction
datapacks/Bookshelf/data/bs.schedule/function/schedule/unit/handle.mcfunction
docs/CHANGELOG.md

🐛 Fix schedule storage execution context

---

datapacks/Bookshelf/data/bs.vector/test/basis_rot_3d.mcfunction
datapacks/Bookshelf/data/bs.vector/test/cartesian_to_spherical.mcfunction
datapacks/Bookshelf/data/bs.vector/test/length.mcfunction
datapacks/Bookshelf/data/bs.vector/test/normalize.mcfunction
datapacks/Bookshelf/data/bs.vector/test/spherical_to_cartesian.mcfunction
datapacks/Bookshelf/data/bs.xp/function/__load__.mcfunction
datapacks/Bookshelf/data/bs.xp/function/__unload__.mcfunction
datapacks/Bookshelf/data/bs.xp/function/add/progress/progress.mcfunction
datapacks/Bookshelf/data/bs.xp/function/get/remaining_points.mcfunction
datapacks/Bookshelf/data/bs.xp/function/get/total_points/range_1.mcfunction
datapacks/Bookshelf/data/bs.xp/function/get/total_points/range_2.mcfunction
datapacks/Bookshelf/data/bs.xp/function/get/total_points/range_3.mcfunction
datapacks/Bookshelf/data/bs.xp/function/get/total_points/total_points.mcfunction
datapacks/Bookshelf/data/bs.xp/function/set/progress/progress.mcfunction
datapacks/Bookshelf/data/bs.xp/test/add/points.mcfunction
datapacks/Bookshelf/data/bs.xp/test/get/max_points.mcfunction
datapacks/Bookshelf/data/bs.xp/test/get/progress.mcfunction
datapacks/Bookshelf/data/bs.xp/test/get/remaining_points.mcfunction
datapacks/Bookshelf/data/bs.xp/test/get/total_points.mcfunction
datapacks/Bookshelf/data/bs.xp/test/set/points.mcfunction
datapacks/Bookshelf/data/bs.xp/test/set/total_points.mcfunction
docs/CHANGELOG.md

🐛 Fix xp progress at bounds

---

datapacks/Bookshelf/data/bs.view/function/can_see_ata/can_see_ata.mcfunction
datapacks/Bookshelf/data/bs.view/function/can_see_ata/max_distance/get_rpos.mcfunction

⚡️ Optimize `#bs.view:can_see_ata`

---

.env.yml
docs/_static/switcher.json

Update to 2.2.1

---

.github/workflows/release.yml
meta/manifest.json

🐛 ci: misssing checkout in release action

---

docs/_templates/changelog/v3.0.0.md
docs/modules/hitbox.md
docs/modules/view.md
meta/manifest.json
modules/bs.hitbox/data/bs.hitbox/function/get_block/get_block.mcfunction
modules/bs.hitbox/data/bs.hitbox/function/is_in_block/is_in_block.mcfunction
modules/bs.hitbox/data/bs.hitbox/tags/block/can_pass_through.json
modules/bs.hitbox/data/bs.hitbox/tags/block/intangible.json
modules/bs.hitbox/gen_shapes.py
modules/bs.move/data/bs.move/function/collision/check/block/any.mcfunction
modules/bs.raycast/data/bs.raycast/function/check/block/any.mcfunction
modules/bs.view/data/bs.view/function/__load__.mcfunction
modules/bs.view/data/bs.view/tags/block/can_see_through.json

💥 feat!: document and rename block tags

---

docs/modules/generate.md
docs/modules/interaction.md
docs/modules/random.md

📝 docs: homogenize documentation verbs

---

docs/_static/bookshelf.css
docs/conf.py

📝 docs: add max-width to version switcher

---

docs/_static/bookshelf.css
docs/_templates/mention-legales-footer.html

Link mentions-legales link does not work in production
No need for the changelog since it's something new anyway

🐛 fix: mentions-legales documentation link

---

docs/_templates/changelog/v3.0.0.md
docs/modules/move.md
meta/manifest.json
modules/bs.move/data/bs.move/predicate/has_vel.json

✨ feat(bs.move): predicate has_vel is now properly documented

---

docs/_templates/changelog/v3.0.0.md
docs/modules/block.md
modules/bs.block/data/bs.block/function/transform/replace_type.mcfunction

- closes #287
There was no test for this initially and i don't really care for one here. Also i don't really think it's necessary and i'm lazy

✨ feat(bs.block): update `replace_type` to return success status

---

.spyglassrc.json
docs/_templates/changelog/v3.0.0.md
docs/modules/raycast.md
modules/bs.raycast/data/bs.raycast/function/__load__.mcfunction
modules/bs.raycast/data/bs.raycast/function/__unload__.mcfunction
modules/bs.raycast/data/bs.raycast/function/collide/block.mcfunction
modules/bs.raycast/data/bs.raycast/function/collide/cube.mcfunction
modules/bs.raycast/data/bs.raycast/function/collide/entity.mcfunction
modules/bs.raycast/data/bs.raycast/function/collide/shape.mcfunction
modules/bs.raycast/data/bs.raycast/function/collide/size.mcfunction
modules/bs.raycast/data/bs.raycast/function/compute/hit_point.mcfunction
modules/bs.raycast/data/bs.raycast/function/run.mcfunction

✨ feat(bs.raycast): add lambda values to callbacks

---

bookshelf/plugins/auto_log_format.py
modules/bs.health/data/bs.health/function/__load__.mcfunction
modules/bs.random/data/bs.random/function/__load__.mcfunction
modules/bs.schedule/data/bs.schedule/function/__load__.mcfunction
modules/bs.sidebar/data/bs.sidebar/function/__load__.mcfunction
modules/config.json

🔨 build: add a beet plugin to setup the logger when needed

---

.github/PULL_REQUEST_TEMPLATE.md

📝 docs: include metadata update in pr template tasks

---

docs/contribute/debug-tools.md

📝 docs: update packtest commands and directives

---

bookshelf/templates/load/bundle/append.jinja
bookshelf/templates/load/process/validate.jinja

✨ feat: add server log to version resolution

---

bookshelf/definitions.py

🗃️ chore: bump bookshelf to 3.0.0

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

⚙️ ci: update release workflows

---

.github/workflows/prerelease.yml

⚙️ ci: fix nightly release workflow

---

docs/changelog/v3.0.0.md

📝 docs: update changelog to mention earlier the different shipping solution

---

docs/_static/bookshelf.css

📝 docs: fix version switcher size

---

data/manifest.json
docs/changelog/v3.0.1.md
modules/bs.spline/module.json
modules/bs.string/module.json

🛠️ chore: fix module tag from default to runtime

---

bookshelf/helpers.py

🔨 build: ensure consistent json generation

---

docs/quickstart.md

📝 docs: fix quickstart beet configuration

---

data/versions.json
docs/_static/switcher.json

🛠️ chore: release v3.0.1

---

.github/workflows/metadata.yml
.github/workflows/release-nightly.yml
.github/workflows/release-pr.yml
.github/workflows/review.yml

⚙️ ci: optimize workflows with concurrency options

---

modules/bs.hitbox/gen_shapes.py

🔨 build(bs.hitbox): ensure consistent json generation

---

data/manifest.json
docs/changelog/v3.0.2.md
modules/bs.dump/data/bs.dump/function/key/get.mcfunction
modules/bs.dump/data/bs.dump/tags/function/var.json

🐛 fix(bs.dump): support compounds with single-letter keys

---

data/manifest.json
docs/changelog/v3.1.0.md
modules/bs.dump/data/bs.dump/function/interpret/nbt/nbt.mcfunction
modules/bs.dump/data/bs.dump/tags/function/var.json

🐛 fix(bs.dump): remove unwanted undefined in var output

---

data/manifest.json
docs/changelog/v3.1.0.md
modules/bs.raycast/data/bs.raycast/function/collide/block.mcfunction
modules/bs.raycast/data/bs.raycast/function/collide/entity.mcfunction
modules/bs.raycast/data/bs.raycast/tags/function/run.json

✨ feat(bs.raycast): compute all lambda data before running callbacks
